TraveSim Adapters: travesim::udp::Receiver Class Reference
travesim::udp::Receiver Class Reference abstract
Receiver class using UDP.
#include "receiver.hpp"
Public Member Functions
Receiver (const std::string receiver_address, const short receiver_port)
Construct a new Receiver object.
virtual ~Receiver ()
Destroy the Receiver object.
size_t receive (char *buffer, const size_t buffer_size)
Receive data using UDP.
size_t receive_latest (char *buffer, const size_t buffer_size)
Receive the latest data using UDP.
void force_specific_source (bool specific_source)
Set wheter to enable any source or source specific. True for specific source, false for any source, default is false.
void set_receiver_endpoint (const std::string receiver_address, const short receiver_port)
Set the receiver endpoint.
void reset (void)
Reset the receiver.
Protected Member Functions
virtual void open_socket ()=0
Open the socket with the desired options.
virtual void close_socket ()
Close the socket.
Protected Attributes
boost::asio::ip::udp::socket * socket
boost::asio::ip::udp::endpoint receiver_endpoint
Private Member Functions
void validate_sender_endpoint (boost::asio::ip::udp::endpoint current_sender_endpoint)
Validate whether the current sender endpoint matches the first sender endpoint when using specific source.
Private Attributes
boost::asio::io_context io_context
boost::asio::ip::udp::endpoint sender_endpoint
bool specific_source
Detailed Description
Receiver class using UDP.
Definition at line 25 of file receiver.hpp.
Constructor & Destructor Documentation
Receiver()
travesim::udp::Receiver::Receiver (const std::string receiver_address, const short receiver_port)
Construct a new Receiver object.
Parameters
receiver_address Address where to send data
receiver_port Port where to send data
Note
open_socket() must be called in the child's constructor
Definition at line 32 of file receiver.cpp.
{
     this->set_receiver_endpoint(receiver_address, receiver_port);
     this->force_specific_source(false);
     this->socket = new boost::asio::ip::udp::socket(io_context);
 };
References force_specific_source(), io_context, set_receiver_endpoint(), and socket.
~Receiver()
travesim::udp::Receiver::~Receiver () virtual
Destroy the Receiver object.
Note
close_socket() must be called in the child's destructor
Definition at line 40 of file receiver.cpp.
                     {
     delete this->socket;
 };
References socket.
Member Function Documentation
close_socket()
void travesim::udp::Receiver::close_socket () protected virtual
Close the socket.
Reimplemented in travesim::udp::MulticastReceiver.
Definition at line 128 of file receiver.cpp.
{
     if (this->socket->is_open()) {
         this->socket->close();
     }
 };
References socket.
force_specific_source()
void travesim::udp::Receiver::force_specific_source (bool specific_source)
Set wheter to enable any source or source specific. True for specific source, false for any source, default is false.
Parameters
specific_source Whether to enable source specific or not.
Definition at line 108 of file receiver.cpp.
{
     this->specific_source = specific_source;
 };
References specific_source.
open_socket()
virtual void travesim::udp::Receiver::open_socket () protected pure virtual
Open the socket with the desired options.
Example:
// Create the socket so that multiple may be bound to the same address.
this->socket->open(this->receiver_endpoint.protocol());
// Set socket options
// Bind to endpoint
this->socket->bind(this->receiver_endpoint);
// Set blocking mode
this->socket->non_blocking(true);
Implemented in travesim::udp::MulticastReceiver, and travesim::udp::UnicastReceiver.
receive()
size_t travesim::udp::Receiver::receive (char * buffer, const size_t buffer_size)
Receive data using UDP.
Parameters
buffer Buffet to store data
buffer_size Size of the buffer where to store data
Returns
size_t Number of bytes received
Todo:
sender_endpoint loggin?
Definition at line 44 of file receiver.cpp.
{
     size_t bytes_received;
     boost::system::error_code ec;
     boost::asio::ip::udp::endpoint current_endpoint;
     bytes_received =
         this->socket->receive_from(boost::asio::buffer(buffer, buffer_size), current_endpoint, NO_FLAGS, ec);
     this->validate_sender_endpoint(current_endpoint);
     switch (ec.value()) {
         case boost::system::errc::success: {
             /**
              * @todo sender_endpoint loggin?
              */
             break;
         }
         case boost::asio::error::would_block: {
             bytes_received = 0;
             break;
         }
         default: {
             throw boost::system::system_error(ec);
         }
     }
     return bytes_received;
 };
References NO_FLAGS, socket, and validate_sender_endpoint().
receive_latest()
size_t travesim::udp::Receiver::receive_latest (char * buffer, const size_t buffer_size)
Receive the latest data using UDP.
Parameters
buffer Buffet to store data
buffer_size Size of the buffer where to store data
Returns
size_t Number of bytes received
Todo:
sender_endpoint loggin?
Definition at line 75 of file receiver.cpp.
{
     size_t bytes_received;
     boost::system::error_code ec;
     boost::asio::ip::udp::endpoint current_endpoint;
     do {
         bytes_received =
             this->socket->receive_from(boost::asio::buffer(buffer, buffer_size), current_endpoint, NO_FLAGS, ec);
     } while (this->socket->available() > 0);
     this->validate_sender_endpoint(current_endpoint);
     switch (ec.value()) {
         case boost::system::errc::success: {
             /**
              * @todo sender_endpoint loggin?
              */
             break;
         }
         case boost::asio::error::would_block: {
             bytes_received = 0;
             break;
         }
         default: {
             throw boost::system::system_error(ec);
         }
     }
     return bytes_received;
 };
References NO_FLAGS, socket, and validate_sender_endpoint().
reset()
void travesim::udp::Receiver::reset (void)
Reset the receiver.
Definition at line 117 of file receiver.cpp.
{
     this->sender_endpoint = INVALID_ENDPOINT;
     this->close_socket();
     this->open_socket();
 };
References close_socket(), INVALID_ENDPOINT, open_socket(), and sender_endpoint.
set_receiver_endpoint()
void travesim::udp::Receiver::set_receiver_endpoint (const std::string receiver_address, const short receiver_port)
Set the receiver endpoint.
Parameters
receiver_address Address where to send data
receiver_port Port where to send data
Warning
reset() must be called after changing the endpoint
Definition at line 112 of file receiver.cpp.
{
     const boost::asio::ip::address receiver_boost_addr = boost::asio::ip::address::from_string(receiver_address);
     this->receiver_endpoint = boost::asio::ip::udp::endpoint(receiver_boost_addr, receiver_port);
 };
References receiver_endpoint.
validate_sender_endpoint()
void travesim::udp::Receiver::validate_sender_endpoint (boost::asio::ip::udp::endpoint current_sender_endpoint) inline private
Validate whether the current sender endpoint matches the first sender endpoint when using specific source.
Parameters
current_sender_endpoint The endpoint from where the last data came from
Exceptions
std::runtime_error When messages from multiple senders are received and any-source is not enabled.
Definition at line 138 of file receiver.cpp.
{
     if (this->specific_source) {
         if (this->sender_endpoint == INVALID_ENDPOINT) {
             this->sender_endpoint = current_sender_endpoint;
         } else if (this->sender_endpoint != current_sender_endpoint) {
             if (current_sender_endpoint != INVALID_ENDPOINT) {
                 std::string error_msg = "Error in receiver. Any-source not enabled.";
                 throw std::runtime_error(error_msg);
             }
         }
     }
 };
References INVALID_ENDPOINT, sender_endpoint, and specific_source.
Member Data Documentation
io_context
boost::asio::io_context travesim::udp::Receiver::io_context private
boost/asio I/O execution context
Definition at line 116 of file receiver.hpp.
receiver_endpoint
boost::asio::ip::udp::endpoint travesim::udp::Receiver::receiver_endpoint protected
Receiver address and port pair
Definition at line 89 of file receiver.hpp.
sender_endpoint
boost::asio::ip::udp::endpoint travesim::udp::Receiver::sender_endpoint private
Sender address and port pair
Definition at line 118 of file receiver.hpp.
socket
boost::asio::ip::udp::socket* travesim::udp::Receiver::socket protected
Network socket
Definition at line 88 of file receiver.hpp.
specific_source
bool travesim::udp::Receiver::specific_source private
True for specific source, false for any source, default is false
Definition at line 120 of file receiver.hpp.
The documentation for this class was generated from the following files:
include/travesim_adapters/udp/receiver.hpp
src/lib/udp/receiver.cpp