TraveSim Adapters: src/lib/configurers/test/configurers_utils.test.cpp File Reference
configurers_utils.test.cpp File Reference
Test configurers utilitary functions.
#include <ros/ros.h>
#include <gtest/gtest.h>
#include "travesim_adapters/configurers/configurers_utils.hpp"
Functions
TEST (configurers_utils, ipv4_string_to_uint)
TEST (configurers_utils, check_valid_ip)
TEST (configurers_utils, get_error_msg)
int main (int argc, char **argv)
Detailed Description
Test configurers utilitary functions.
Author
Lucas Haug lucas.nosp@m..hau.nosp@m.g@thu.nosp@m.nera.nosp@m.tz.or.nosp@m.g
Date
06/2021
Copyright
MIT License - Copyright (c) 2021 ThundeRatz
Definition in file configurers_utils.test.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 99 of file configurers_utils.test.cpp.
{
     testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST() [1/3]
TEST (configurers_utils , ipv4_string_to_uint)
Definition at line 23 of file configurers_utils.test.cpp.
 {
     uint ip_uint[4] = {0};
     EXPECT_TRUE(travesim::ipv4_string_to_uint("1.1.1.1", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {1, 1, 1, 1}));
     ip_uint[0] = 0;
     ip_uint[1] = 0;
     ip_uint[2] = 0;
     ip_uint[3] = 0;
     EXPECT_TRUE(travesim::ipv4_string_to_uint("127.220.4.32", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {127, 220, 4, 32}));
     ip_uint[0] = 0;
     ip_uint[1] = 0;
     ip_uint[2] = 0;
     ip_uint[3] = 0;
     EXPECT_FALSE(travesim::ipv4_string_to_uint("@.b.C.3", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {0, 0, 0, 0}));
     ip_uint[0] = 0;
     ip_uint[1] = 0;
     ip_uint[2] = 0;
     ip_uint[3] = 0;
     EXPECT_FALSE(travesim::ipv4_string_to_uint("123,123,123,123", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {123, 0, 0, 0}));
     ip_uint[0] = 0;
     ip_uint[1] = 0;
     ip_uint[2] = 0;
     ip_uint[3] = 0;
     EXPECT_FALSE(travesim::ipv4_string_to_uint("Test", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {0, 0, 0, 0}));
     ip_uint[0] = 0;
     ip_uint[1] = 0;
     ip_uint[2] = 0;
     ip_uint[3] = 0;
     EXPECT_FALSE(travesim::ipv4_string_to_uint("239.64.73.Q", ip_uint));
     EXPECT_TRUE(testing::internal::ArrayEq(ip_uint, {239, 64, 73, 0}));
 }
References travesim::ipv4_string_to_uint().
TEST() [2/3]
TEST (configurers_utils , check_valid_ip)
Definition at line 71 of file configurers_utils.test.cpp.
 {
     using namespace travesim;
     EXPECT_EQ(check_valid_ip("127.0.0.2", "127.0.0.0", "127.255.255.0"), IPValidation::VALID);
     EXPECT_EQ(check_valid_ip("225.0.64.2", "224.0.0.0", "239.255.34.255"), IPValidation::VALID);
     EXPECT_EQ(check_valid_ip("227.0.0.2", "227.0.0.0", "A.255.255.0"), IPValidation::INVALID_FORMAT);
     EXPECT_EQ(check_valid_ip("127.0.0,2", "127.0.0.0", "127.255.255.0"), IPValidation::INVALID_FORMAT);
     EXPECT_EQ(check_valid_ip("127.0.512.2", "127.0.0.0", "127.255.255.0"), IPValidation::INVALID_NUMBERS);
     EXPECT_EQ(check_valid_ip("1024.0.0.2", "127.0.0.0", "127.255.255.0"), IPValidation::INVALID_NUMBERS);
     EXPECT_EQ(check_valid_ip("127.0.0.2", "127.0.0.255", "127.255.255.0"), IPValidation::OUT_OF_RANGE);
     EXPECT_EQ(check_valid_ip("224.0.0.2", "127.0.0.0", "127.255.255.0"), IPValidation::OUT_OF_RANGE);
 }
References travesim::check_valid_ip(), travesim::INVALID_FORMAT, travesim::INVALID_NUMBERS, travesim::OUT_OF_RANGE, and travesim::VALID.
TEST() [3/3]
TEST (configurers_utils , get_error_msg)
Definition at line 85 of file configurers_utils.test.cpp.
 {
     using namespace travesim;
     EXPECT_EQ(get_error_msg(IPValidation::VALID), "No error.");
     EXPECT_EQ(get_error_msg(IPValidation::INVALID_FORMAT), "The IP string is wrong formatted.");
     EXPECT_EQ(get_error_msg(IPValidation::INVALID_NUMBERS),
               "The numbers on the ip are not representable by 8 bits.");
     EXPECT_EQ(get_error_msg(IPValidation::OUT_OF_RANGE),
               "The IP is not in the specified range. Hover over the parameterto see the range.");
     EXPECT_EQ(get_error_msg(IPValidation(42)), "No error.");
 }
References travesim::get_error_msg(), travesim::INVALID_FORMAT, travesim::INVALID_NUMBERS, travesim::OUT_OF_RANGE, and travesim::VALID.