TraveSim Adapters: src/bin/vision_adapter.cpp File Reference
vision_adapter.cpp File Reference
Vision adapter executable file.
#include <ros/ros.h>
#include <ros/console.h>
#include <gazebo_msgs/ModelStates.h>
#include "travesim_adapters/ros/vision_receiver.hpp"
#include "travesim_adapters/data/converter/ros_side.hpp"
#include "travesim_adapters/data/field_state.hpp"
#include "travesim_adapters/data/robot_state.hpp"
#include "travesim_adapters/data/entity_state.hpp"
#include "travesim_adapters/protobuf/vision_sender.hpp"
#include "travesim_adapters/configurers/vision_configurer.hpp"
#include <iostream>
Functions
int main (int argc, char **argv)
Detailed Description
Vision adapter executable file.
Author
Felipe Gomes de Melo felip.nosp@m.e.go.nosp@m.mes@t.nosp@m.hund.nosp@m.eratz.nosp@m..org
Lucas Haug lucas.nosp@m..hau.nosp@m.g@thu.nosp@m.nder.nosp@m.atz.o.nosp@m.rg
Date
06/2021
Copyright
MIT License - Copyright (c) 2021 ThundeRatz
See also
VisionReceiver
VisionSender
Definition in file vision_adapter.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 31 of file vision_adapter.cpp.
{
     ros::init(argc, argv, "vision_adapter");
     ros::NodeHandle nh;
     travesim::VisionConfigurer vision_configurer;
     int32_t multicast_port = vision_configurer.get_port();
     std::string multicast_address_str = vision_configurer.get_address();
     travesim::ros_side::VisionReceiver vision_receiver;
     travesim::proto::VisionSender vision_sender(multicast_address_str, multicast_port);
     int robots_per_team;
     ros::param::param<int>("/robots_per_team", robots_per_team, travesim::TeamsFormation::THREE_ROBOTS_PER_TEAM);
     travesim::TeamsFormation teams_formation;
     if (robots_per_team == int(travesim::TeamsFormation::THREE_ROBOTS_PER_TEAM)) {
         teams_formation = travesim::TeamsFormation::THREE_ROBOTS_PER_TEAM;
     } else if (robots_per_team == int(travesim::TeamsFormation::FIVE_ROBOTS_PER_TEAM)) {
         teams_formation = travesim::TeamsFormation::FIVE_ROBOTS_PER_TEAM;
     } else {
         ROS_ERROR_STREAM("Invalid number of robots per team");
         ros::shutdown();
     }
     travesim::FieldState field_state(teams_formation);
     gazebo_msgs::ModelStates::ConstPtr world_state;
     ROS_INFO_STREAM("Vision adapter config:" << std::endl << vision_configurer);
     field_state.time_step = 0;
     while (ros::ok()) {
         if (vision_receiver.receive(&world_state)) {
             field_state = travesim::converter::ModelStates_to_FieldState(world_state, teams_formation);
             vision_sender.send(&field_state);
             field_state.time_step++;
         }
         if (vision_configurer.get_reset()) {
             multicast_port = vision_configurer.get_port();
             multicast_address_str = vision_configurer.get_address();
             vision_sender.set_multicast_endpoint(multicast_address_str, multicast_port);
             ROS_INFO_STREAM("Vision adapter config:" << std::endl << vision_configurer);
         }
         ros::spinOnce();
     }
 }
References travesim::FIVE_ROBOTS_PER_TEAM, travesim::VisionConfigurer::get_address(), travesim::VisionConfigurer::get_port(), travesim::AdapterConfigurer< AdapterConfigType >::get_reset(), travesim::converter::ModelStates_to_FieldState(), travesim::ros_side::VisionReceiver::receive(), travesim::proto::VisionSender::send(), travesim::proto::VisionSender::set_multicast_endpoint(), travesim::THREE_ROBOTS_PER_TEAM, and travesim::FieldState::time_step.