TraveSim Adapters: travesim::converter Namespace Reference
travesim::converter Namespace Reference
Functions
travesim::Vector2D Point_to_Vector2D (geometry_msgs::Point *point)
Function to convert geometry_msgs::Point to travesim::Vector2D.
travesim::Vector2D Vector3_to_Vector2D (geometry_msgs::Vector3 *vector3)
Function to convert geometry_msgs::Vector3 to travesim::Vector2D.
travesim::EntityState ModelState_to_EntityState (gazebo_msgs::ModelState *model_state)
Function to convert gazebo_msgs::ModelState to travesim::EntityState.
travesim::RobotState ModelState_to_RobotState (gazebo_msgs::ModelState *model_state, bool is_yellow=true, int id=0)
Function to convert gazebo_msgs::ModelState to travesim::RobotState.
geometry_msgs::Vector3 Vector2D_to_Vector3 (Vector2D *vector2d)
Function to convert travesim::Vector2D to geometry_msgs::Vector3.
geometry_msgs::Point Vector2D_to_Point (Vector2D *vector2d, double z=DEFAULT_Z_VALUE_BALL)
Function to convert travesim::Vector2D to geometry_msgs::Point.
gazebo_msgs::ModelState EntityState_to_ModelState (EntityState *entity_state, double z=DEFAULT_Z_VALUE_BALL)
Function to convert travesim::EntityState to gazebo_msgs::ModelState.
gazebo_msgs::ModelState RobotState_to_ModelState (RobotState *robot_state, double z=DEFAULT_Z_VALUE_ROBOT)
Function to convert travesim::RobotState to gazebo_msgs::ModelState.
travesim::FieldState ModelStates_to_FieldState (gazebo_msgs::ModelStates::ConstPtr model_states, TeamsFormation teams_formation)
Function to convert gazebo_msgs::ModelStates to travesim::FieldState.
Function Documentation
EntityState_to_ModelState()
gazebo_msgs::ModelState travesim::converter::EntityState_to_ModelState (EntityState * entity_state, double z = DEFAULT_Z_VALUE_BALL)
Function to convert travesim::EntityState to gazebo_msgs::ModelState.
Parameters
entity_state Data to be converted
Returns
gazebo_msgs::ModelState Converted data
Definition at line 86 of file ros_side.cpp.
{
     gazebo_msgs::ModelState retval;
     retval.model_name = DEFAULT_ENTITY_NAME;
     retval.reference_frame = DEFAULT_REFERENCE_FRAME;
     retval.pose.position = Vector2D_to_Point(&entity_state->position, z);
     retval.pose.orientation.w = cos(entity_state->angular_position/2);
     retval.pose.orientation.x = 0;
     retval.pose.orientation.y = 0;
     retval.pose.orientation.z = sin(entity_state->angular_position/2);
     retval.twist.linear = Vector2D_to_Vector3(&entity_state->velocity);
     retval.twist.angular.x = 0;
     retval.twist.angular.y = 0;
     retval.twist.angular.z = entity_state->angular_velocity;
     return retval;
 }
References travesim::EntityState::angular_position, travesim::EntityState::angular_velocity, DEFAULT_ENTITY_NAME, DEFAULT_REFERENCE_FRAME, travesim::EntityState::position, Vector2D_to_Point(), Vector2D_to_Vector3(), and travesim::EntityState::velocity.
ModelState_to_EntityState()
EntityState travesim::converter::ModelState_to_EntityState (gazebo_msgs::ModelState * model_state)
Function to convert gazebo_msgs::ModelState to travesim::EntityState.
Parameters
model_state Data to be converted
Returns
travesim::EntityState Converted data
Definition at line 63 of file ros_side.cpp.
{
     EntityState retval;
     retval.position = Point_to_Vector2D(&model_state->pose.position);
     retval.angular_position = quaternion_to_theta(model_state->pose.orientation.w, model_state->pose.orientation.x,
                                                   model_state->pose.orientation.y, model_state->pose.orientation.z);
     retval.velocity = Vector3_to_Vector2D(&model_state->twist.linear);
     retval.angular_velocity = model_state->twist.angular.z;
     return retval;
 }
References travesim::EntityState::angular_position, travesim::EntityState::angular_velocity, Point_to_Vector2D(), travesim::EntityState::position, quaternion_to_theta, Vector3_to_Vector2D(), and travesim::EntityState::velocity.
ModelState_to_RobotState()
RobotState travesim::converter::ModelState_to_RobotState (gazebo_msgs::ModelState * model_state, bool is_yellow = true, int id = 0)
Function to convert gazebo_msgs::ModelState to travesim::RobotState.
Parameters
model_state Data to be converted
is_yellow True if the robot is from the yellow team, false otherwise
id Id number of the robot
Returns
travesim::RobotState Converte data
Definition at line 78 of file ros_side.cpp.
{
     EntityState tmp = ModelState_to_EntityState(model_state);
     RobotState retval(&tmp, is_yellow, id);
     return retval;
 }
References ModelState_to_EntityState().
ModelStates_to_FieldState()
FieldState travesim::converter::ModelStates_to_FieldState (gazebo_msgs::ModelStates::ConstPtr model_states, TeamsFormation teams_formation)
Function to convert gazebo_msgs::ModelStates to travesim::FieldState.
Parameters
model_states Data to be converted
teams_formation Number of robots per team
Returns
travesim::FieldState Converted data
This lookup table will map model_name -> field_state data location, so we can acess field_state elements from their's names
This lookup table will map model_name -> field_state data location, so we can acess field_state elements from their's names
Definition at line 117 of file ros_side.cpp.
{
     static FieldState field_state(teams_formation);
     /**
      * @brief This lookup table will map model_name -> field_state data location,
      *        so we can acess field_state elements from their's names
      */
     static lookup_table_t lookup_table;
     lookup_table[BALL_NAME] = &field_state.ball;
     for (uint8_t i = 0; i < field_state.robots_per_team; i++) {
         lookup_table[ROBOT_NAME("yellow", i)] = &field_state.yellow_team[i];
         lookup_table[ROBOT_NAME("blue", i)] = &field_state.blue_team[i];
     }
     uint32_t size = model_states->name.size();
     for (uint32_t i = 0; i < size; i++) {
         EntityState* entity_state_ptr = lookup_table[model_states->name[i]];
         if (entity_state_ptr != nullptr) {
             gazebo_msgs::ModelState model_state;
             model_state.pose = model_states->pose[i];
             model_state.twist = model_states->twist[i];
             model_state.model_name = model_states->name[i];
             model_state.reference_frame = DEFAULT_REFERENCE_FRAME;
             (*entity_state_ptr) = ModelState_to_EntityState(&model_state);
         }
     }
     return field_state;
 }
References travesim::FieldState::ball, BALL_NAME, travesim::FieldState::blue_team, DEFAULT_REFERENCE_FRAME, ModelState_to_EntityState(), ROBOT_NAME, travesim::FieldState::robots_per_team, and travesim::FieldState::yellow_team.
Point_to_Vector2D()
Vector2D travesim::converter::Point_to_Vector2D (geometry_msgs::Point * point)
Function to convert geometry_msgs::Point to travesim::Vector2D.
Parameters
point Data to be converted
Returns
travesim::Vector2D Converted data
Definition at line 25 of file ros_side.cpp.
{
     Vector2D retval;
     retval.x = point->x;
     retval.y = point->y;
     return retval;
 }
References travesim::Vector2D::x, and travesim::Vector2D::y.
RobotState_to_ModelState()
gazebo_msgs::ModelState travesim::converter::RobotState_to_ModelState (RobotState * robot_state, double z = DEFAULT_Z_VALUE_ROBOT)
Function to convert travesim::RobotState to gazebo_msgs::ModelState.
Parameters
entity_state Data to be converted
Returns
gazebo_msgs::ModelState Converted data
Definition at line 108 of file ros_side.cpp.
{
     gazebo_msgs::ModelState retval = EntityState_to_ModelState(dynamic_cast<EntityState*>(robot_state), z);
     std::string base_name = robot_state->is_yellow ? "yellow_team/robot_" : "blue_team/robot_";
     retval.model_name = base_name.append(std::to_string(robot_state->id));
     return retval;
 }
References EntityState_to_ModelState(), travesim::RobotState::id, and travesim::RobotState::is_yellow.
Vector2D_to_Point()
geometry_msgs::Point travesim::converter::Vector2D_to_Point (Vector2D * vector2d, double z = DEFAULT_Z_VALUE_BALL)
Function to convert travesim::Vector2D to geometry_msgs::Point.
Parameters
vector2d Data to be converted
Returns
geometry_msgs::Point Converted data
Definition at line 53 of file ros_side.cpp.
{
     geometry_msgs::Point retval;
     retval.x = vector2d->x;
     retval.y = vector2d->y;
     retval.z = z;
     return retval;
 }
References travesim::Vector2D::x, and travesim::Vector2D::y.
Vector2D_to_Vector3()
geometry_msgs::Vector3 travesim::converter::Vector2D_to_Vector3 (Vector2D * vector2d)
Function to convert travesim::Vector2D to geometry_msgs::Vector3.
Parameters
vector2d Data to be converted
Returns
geometry_msgs::Vector3 Converted data
Definition at line 43 of file ros_side.cpp.
{
     geometry_msgs::Vector3 retval;
     retval.x = vector2d->x;
     retval.y = vector2d->y;
     retval.z = 0;
     return retval;
 }
References travesim::Vector2D::x, and travesim::Vector2D::y.
Vector3_to_Vector2D()
Vector2D travesim::converter::Vector3_to_Vector2D (geometry_msgs::Vector3 * vector3)
Function to convert geometry_msgs::Vector3 to travesim::Vector2D.
Parameters
vector3 Data to be converted
Returns
travesim::Vector2D Converted data
Definition at line 34 of file ros_side.cpp.
{
     Vector2D retval;
     retval.x = vector3->x;
     retval.y = vector3->y;
     return retval;
 }
References travesim::Vector2D::x, and travesim::Vector2D::y.