TraveSim Adapters: travesim::ros_side::ReplacerSender Class Reference
travesim::ros_side::ReplacerSender Class Reference
#include "replacer_sender.hpp"
Public Member Functions
ReplacerSender ()
Construct a new Replacer Sender object.
bool set_models_state (state_vector_t *model_states)
Set state of multiple entities.
bool set_model_state (gazebo_msgs::ModelState model_state)
Set the state of one entity.
bool send_command (simulation_command_t command)
Send command to gazebo.
void reconnect_service_client ()
Attempts to reconnect gz_service ServiceClient if connection dropped.
Private Attributes
ros::NodeHandlePtr _nh
ros::ServiceClient gz_service
Detailed Description
Definition at line 37 of file replacer_sender.hpp.
Constructor & Destructor Documentation
ReplacerSender()
travesim::ros_side::ReplacerSender::ReplacerSender ()
Construct a new Replacer Sender object.
Definition at line 23 of file replacer_sender.cpp.
{
     _nh = ros::NodeHandlePtr(new ros::NodeHandle());
     this->reconnect_service_client();
 }
References _nh, and reconnect_service_client().
Member Function Documentation
reconnect_service_client()
void travesim::ros_side::ReplacerSender::reconnect_service_client ()
Attempts to reconnect gz_service ServiceClient if connection dropped.
If the connection dropped, we try to reconnect
Definition at line 28 of file replacer_sender.cpp.
{
     /**
      * @brief If the connection dropped, we try to reconnect
      */
     if (!this->gz_service.isValid()) {
         this->gz_service = this->_nh->serviceClient<gazebo_msgs::SetModelState>("/gazebo/set_model_state");
     }
 }
References _nh, and gz_service.
send_command()
bool travesim::ros_side::ReplacerSender::send_command (simulation_command_t command)
Send command to gazebo.
Parameters
command
Returns
true If sucessfull
false If any error occured
Definition at line 65 of file replacer_sender.cpp.
{
     static std::unordered_map<simulation_command_t, std::string> topics_table({
                 {travesim::ros_side::PAUSE, "/gazebo/pause_physics" },
                 {travesim::ros_side::RESUME, "/gazebo/unpause_physics"},
                 {travesim::ros_side::RESET_WORLD, "/gazebo/reset_world"},
                 {travesim::ros_side::RESET_SIMULATION, "/gazebo/reset_simulation"},
             });
     std_srvs::Empty msg;
     if (topics_table[command] == "") {
         return false;
     } else {
         ros::service::call(topics_table[command], msg);
         return true;
     }
 }
References travesim::ros_side::PAUSE, travesim::ros_side::RESET_SIMULATION, travesim::ros_side::RESET_WORLD, and travesim::ros_side::RESUME.
set_model_state()
bool travesim::ros_side::ReplacerSender::set_model_state (gazebo_msgs::ModelState model_state)
Set the state of one entity.
Parameters
model_state ModelState to be set
Note
The affected entity is infered from the model_name of the ModelState
Returns
true If sucessfull
false If any error occured
Definition at line 37 of file replacer_sender.cpp.
{
     static gazebo_msgs::SetModelStateRequest request;
     static gazebo_msgs::SetModelStateResponse response;
     this->reconnect_service_client();
     request.model_state = model_state;
     bool status = this->gz_service.call(request, response);
     if (!(status && response.success)) {
         ROS_ERROR_STREAM("Error while calling set_model_state " << model_state);
         return false;
     }
     return true;
 }
References gz_service, and reconnect_service_client().
set_models_state()
bool travesim::ros_side::ReplacerSender::set_models_state (state_vector_t * model_states)
Set state of multiple entities.
Parameters
model_states Vector of states to be set
Note
The affected entity is infered from the model_name of each ModelState
Returns
true If sucessfull
false If any error occured
Definition at line 54 of file replacer_sender.cpp.
{
     for (uint32_t i = 0; i < model_states->size(); i++) {
         if (!this->set_model_state(model_states->at(i))) {
             ROS_ERROR_STREAM("Error while calling set_team_state at i = " << i);
             return false;
         }
     }
     return true;
 }
References set_model_state().
Member Data Documentation
_nh
ros::NodeHandlePtr travesim::ros_side::ReplacerSender::_nh private
Definition at line 39 of file replacer_sender.hpp.
gz_service
ros::ServiceClient travesim::ros_side::ReplacerSender::gz_service private
Definition at line 41 of file replacer_sender.hpp.
The documentation for this class was generated from the following files:
include/travesim_adapters/ros/replacer_sender.hpp
src/lib/ros/replacer_sender.cpp