TraveSim Adapters: travesim::udp::MulticastReceiver Class Reference
travesim::udp::MulticastReceiver Class Reference
Receiver class using UDP in multicast mode.
#include "multicast_receiver.hpp"
Public Member Functions
MulticastReceiver (const std::string multicast_address, const short multicast_port, const std::string receiver_address)
Construct a new Multicast Receiver object.
MulticastReceiver (const std::string multicast_address, const short multicast_port)
Construct a new Multicast Receiver object.
~MulticastReceiver ()
Destroy the Multicast Receiver object.
void set_multicast_address (const std::string multicast_address)
Set the multicast address.
Public Member Functions inherited from travesim::udp::Receiver
Receiver (const std::string receiver_address, const short receiver_port)
Construct a new Receiver object.
virtual ~Receiver ()
Destroy the Receiver object.
size_t receive (char *buffer, const size_t buffer_size)
Receive data using UDP.
size_t receive_latest (char *buffer, const size_t buffer_size)
Receive the latest data using UDP.
void force_specific_source (bool specific_source)
Set wheter to enable any source or source specific. True for specific source, false for any source, default is false.
void set_receiver_endpoint (const std::string receiver_address, const short receiver_port)
Set the receiver endpoint.
void reset (void)
Reset the receiver.
Private Member Functions
void open_socket ()
Open the socket with the desired options.
void close_socket ()
Close the socket.
Private Attributes
boost::asio::ip::address multicast_address
Additional Inherited Members
Protected Attributes inherited from travesim::udp::Receiver
boost::asio::ip::udp::socket * socket
boost::asio::ip::udp::endpoint receiver_endpoint
Detailed Description
Receiver class using UDP in multicast mode.
Definition at line 24 of file multicast_receiver.hpp.
Constructor & Destructor Documentation
MulticastReceiver() [1/2]
travesim::udp::MulticastReceiver::MulticastReceiver (const std::string multicast_address, const short multicast_port, const std::string receiver_address)
Construct a new Multicast Receiver object.
Parameters
multicast_address Multicas group address
multicast_port Multicast group port
receiver_address Receiver address, has a filtering role, setting where the data may be received
Note
The multicast addresses must be in the range 224.0.0.0 through 239.255.255.255, see IPv4 Multicast Address Space Registry or the RFC1112 for more informations.
Definition at line 22 of file multicast_receiver.cpp.
                                                                  : Receiver(receiver_address, multicast_port) {
     this->set_multicast_address(multicast_address);
     this->open_socket();
 };
References open_socket(), and set_multicast_address().
MulticastReceiver() [2/2]
travesim::udp::MulticastReceiver::MulticastReceiver (const std::string multicast_address, const short multicast_port)
Construct a new Multicast Receiver object.
Parameters
multicast_address Multicas group address
multicast_port Multicast group port
Note
Use multicast address as listen address
The multicast addresses must be in the range 224.0.0.0 through 239.255.255.255, see IPv4 Multicast Address Space Registry or the RFC1112 for more informations.
Definition at line 29 of file multicast_receiver.cpp.
                                                                                       :
     MulticastReceiver(multicast_address, multicast_port, multicast_address) {
 };
~MulticastReceiver()
travesim::udp::MulticastReceiver::~MulticastReceiver ()
Destroy the Multicast Receiver object.
Definition at line 33 of file multicast_receiver.cpp.
{
     this->close_socket();
 };
References close_socket().
Member Function Documentation
close_socket()
void travesim::udp::MulticastReceiver::close_socket () private virtual
Close the socket.
Reimplemented from travesim::udp::Receiver.
Definition at line 62 of file multicast_receiver.cpp.
{
     if (this->socket->is_open()) {
         this->socket->set_option(boost::asio::ip::multicast::leave_group(this->multicast_address));
         this->socket->close();
     }
 };
References multicast_address, and travesim::udp::Receiver::socket.
open_socket()
void travesim::udp::MulticastReceiver::open_socket () private virtual
Open the socket with the desired options.
Implements travesim::udp::Receiver.
Definition at line 46 of file multicast_receiver.cpp.
{
     // Create the socket so that multiple may be bound to the same address.
     this->socket->open(this->receiver_endpoint.protocol());
     this->socket->set_option(boost::asio::ip::udp::socket::reuse_address(true));
     this->socket->set_option(boost::asio::ip::multicast::hops(1));
     // Join the multicast group.
     this->socket->set_option(boost::asio::ip::multicast::join_group(this->multicast_address));
     this->socket->bind(this->receiver_endpoint);
     // Use non blocking for syncronous reading
     this->socket->non_blocking(true);
 };
References multicast_address, travesim::udp::Receiver::receiver_endpoint, and travesim::udp::Receiver::socket.
set_multicast_address()
void travesim::udp::MulticastReceiver::set_multicast_address (const std::string multicast_address)
Set the multicast address.
Parameters
multicast_address Multicast group address in a string
Warning
reset() must be called after changing the address
Note
The multicast addresses must be in the range 224.0.0.0 through 239.255.255.255, see IPv4 Multicast Address Space Registry or the RFC1112 for more informations.
Definition at line 37 of file multicast_receiver.cpp.
{
     const boost::asio::ip::address multicast_boost_addr = boost::asio::ip::address::from_string(multicast_address);
     this->multicast_address = multicast_boost_addr;
 };
References multicast_address.
Member Data Documentation
multicast_address
boost::asio::ip::address travesim::udp::MulticastReceiver::multicast_address private
Definition at line 78 of file multicast_receiver.hpp.
The documentation for this class was generated from the following files:
include/travesim_adapters/udp/multicast_receiver.hpp
src/lib/udp/multicast_receiver.cpp