vision_multicast_group:
  address: "224.0.0.1"
  port: 10002

replacer_client:
  address: "127.0.0.1"
  port: 20013

teams_control_client:
  yellow:
    address: "127.0.0.1"
    port: 20012
  blue:
    address: "127.0.0.1"
    port: 20013
