name: Build project with docker
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker build -t adapters .
      - name: Run test
        run: docker run -it adapters
