TraveSim Adapters: src/lib/data/converter/test/ros_side.test.cpp File Reference
ros_side.test.cpp File Reference
#include <ros/ros.h>
#include <ros/console.h>
#include <gtest/gtest.h>
#include <gazebo_msgs/ModelState.h>
#include <geometry_msgs/Vector3.h>
#include <iostream>
#include "travesim_adapters/data/converter/ros_side.hpp"
#include "travesim_adapters/data/robot_state.hpp"
#include "travesim_adapters/ros/vision_receiver.hpp"
Functions
TEST (vector2d_to_vector3, convert_from_vector2d)
TEST (vector2d_to_vector3, convert_from_vector3)
TEST (robot_state_to_model_state, model_name)
TEST (robot_state_to_model_state, angle_conversion)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 79 of file ros_side.test.cpp.
{
     testing::InitGoogleTest(&argc, argv);
     // ros::init(argc, argv, "tester");
     // ros::NodeHandle nh;
     return RUN_ALL_TESTS();
 }
TEST() [1/4]
TEST (vector2d_to_vector3 , convert_from_vector2d)
Definition at line 22 of file ros_side.test.cpp.
 {
     travesim::Vector2D vector2d(2, 4);
     geometry_msgs::Vector3 vector3 = travesim::converter::Vector2D_to_Vector3(&vector2d);
     EXPECT_DOUBLE_EQ(vector3.x, 2);
     EXPECT_DOUBLE_EQ(vector3.y, 4);
 }
References travesim::converter::Vector2D_to_Vector3().
TEST() [2/4]
TEST (vector2d_to_vector3 , convert_from_vector3)
Definition at line 32 of file ros_side.test.cpp.
 {
     geometry_msgs::Vector3 vector3;
     vector3.x = 3;
     vector3.y = -7;
     travesim::Vector2D vector2d = travesim::converter::Vector3_to_Vector2D(&vector3);
     EXPECT_DOUBLE_EQ(vector2d.x, 3);
     EXPECT_DOUBLE_EQ(vector2d.y, -7);
 }
References travesim::converter::Vector3_to_Vector2D(), travesim::Vector2D::x, and travesim::Vector2D::y.
TEST() [3/4]
TEST (robot_state_to_model_state , model_name)
Definition at line 45 of file ros_side.test.cpp.
 {
     travesim::RobotState robot_state;
     EXPECT_EQ(travesim::converter::RobotState_to_ModelState(&robot_state).model_name, "yellow_team/robot_0");
     robot_state.id = 2;
     EXPECT_EQ(travesim::converter::RobotState_to_ModelState(&robot_state).model_name, "yellow_team/robot_2");
     robot_state.is_yellow = false;
     robot_state.id = 0;
     EXPECT_EQ(travesim::converter::RobotState_to_ModelState(&robot_state).model_name,
               "blue_team/robot_0");
     robot_state.id = 1;
     EXPECT_EQ(travesim::converter::RobotState_to_ModelState(&robot_state).model_name,
               "blue_team/robot_1");
 }
References travesim::RobotState::id, travesim::RobotState::is_yellow, and travesim::converter::RobotState_to_ModelState().
TEST() [4/4]
TEST (robot_state_to_model_state , angle_conversion)
Definition at line 67 of file ros_side.test.cpp.
 {
     travesim::RobotState robot_state;
     robot_state.angular_position = -M_PI/3;
     gazebo_msgs::ModelState model_state = travesim::converter::RobotState_to_ModelState(&robot_state);
     EXPECT_DOUBLE_EQ(travesim::converter::ModelState_to_RobotState(&model_state).angular_position,
                      robot_state.angular_position);
 }
References travesim::EntityState::angular_position, travesim::converter::ModelState_to_RobotState(), and travesim::converter::RobotState_to_ModelState().